# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/chengsilin/documents/system_practice/mipsfpga_coe_os/mipsfpga_axi4.tmp/car_dir_v1_0_project/Car_Dir_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/chengsilin/documents/system_practice/mipsfpga_coe_os/mipsfpga_axi4.tmp/car_dir_v1_0_project/Car_Dir_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/chengsilin/Documents/System_Practice/ip_repo/Car_Dir_1.0
  c:/Users/chengsilin/Documents/System_Practice/ip_repo/PWM_1.0
  c:/Users/chengsilin/Documents/System_Practice/ip_repo/PWM_1.0
  c:/Users/chengsilin/Documents/System_Practice/MIPSfpga_Coe_os/xilinx.com_user_MIPS_MicroAptiv_UP_1.0
  c:/Users/chengsilin/Documents/System_Practice/ip_repo
} [current_project]
read_verilog -library xil_defaultlib {
  c:/users/chengsilin/documents/system_practice/ip_repo/car_dir_1.0/hdl/Car_Dir_v1_0_S00_AXI.v
  c:/users/chengsilin/documents/system_practice/ip_repo/car_dir_1.0/hdl/Freq_Div_mod.v
  c:/users/chengsilin/documents/system_practice/ip_repo/car_dir_1.0/hdl/Car_Driver_Int.v
  c:/users/chengsilin/documents/system_practice/ip_repo/car_dir_1.0/hdl/Car_Dir_v1_0.v
}
synth_design -top Car_Dir_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef Car_Dir_v1_0.dcp
catch { report_utilization -file Car_Dir_v1_0_utilization_synth.rpt -pb Car_Dir_v1_0_utilization_synth.pb }
